/**
 * Données par défaut de la home — utilisées comme FALLBACK
 * si la DB ne contient pas encore de sections (avant le seed).
 */
import type { HomeSection } from '@shared/home-sections';

export const DEFAULT_HOME_SECTIONS: HomeSection[] = [
  {
    id: 'hero',
    type: 'hero',
    order: 10,
    backgroundImage: '/uploads/hero/home-header.jpg',
    titleLine1: 'Structuring',
    titleLine2: 'Influence.',
    subtitle: 'Agence de communication stratégique — Casablanca, Maroc — depuis 2005',
    primaryCta: { label: 'Parlez-nous de votre projet', href: '/contact' },
    secondaryCta: { label: 'Lancer mon scoring', href: '/outils/commpulse' },
  },
  {
    id: 'intro',
    type: 'intro',
    order: 20,
    eyebrow: 'Strategic Influence and Brand Architecture',
    title: 'Securing Growth.',
    bodyHtml: `<p>À un certain stade de développement, la communication dépasse la simple recherche de visibilité. Elle devient un enjeu de cohérence et un levier d'influence.</p><p>Basée à Casablanca, <strong>Epitaphe360</strong> est, depuis plus de 20 ans, l'agence de communication des organisations qui exigent l'excellence.</p>`,
    bullets: [
      'La Stabilité — Bâtir une image de marque solide.',
      'La Fluidité — Optimiser vos flux pour une organisation sans friction.',
      'La Crédibilité — Garantir votre autorité auprès de vos partenaires stratégiques.',
      'La Mobilisation — Transformer vos équipes en un collectif engagé.',
      'La Rentabilité — Assurer la pérennité de votre performance économique.',
    ],
    image: '/uploads/hero/agence-com.jpg',
    ctaLabel: 'Découvrir l\'agence',
    ctaHref: '/a-propos',
  },
  { id: 'stats', type: 'stats', order: 30, items: [] },
  {
    id: 'clients',
    type: 'clients',
    order: 40,
    title: 'Ils nous font confiance',
    subtitle: 'Plus de 500 entreprises au Maroc et à l\'international',
    logos: [
      { name: 'Qatar Airways', logo: '/uploads/clients/qatar-airways.png' },
      { name: 'Schneider Electric', logo: '/uploads/clients/schneider-electric.jpg' },
      { name: 'Dell', logo: '/uploads/clients/dell.jpg' },
      { name: 'SNEP', logo: '/uploads/clients/snep.jpg' },
      { name: 'AXA', logo: '/uploads/clients/axa.jpg' },
      { name: 'Ajial', logo: '/uploads/clients/ajial.jpg' },
      { name: 'LafargeHolcim', logo: '/uploads/clients/lafargeholcim.jpg' },
      { name: 'Renault', logo: '/uploads/clients/renault.jpg' },
    ],
    ctaLabel: 'Voir toutes nos références',
    ctaHref: '/nos-references',
  },
  {
    id: 'poles',
    type: 'poles',
    order: 50,
    title: 'Nos pôles d\'expertise',
    subtitle: 'Six axes pour structurer votre influence',
    items: [
      { num: '01', title: 'Communication Interne', desc: 'Synchronisez les énergies pour transformer l\'information en moteur d\'engagement.', href: '/architecture-de-marque' },
      { num: '02', title: 'Marque Employeur', desc: 'Cultivez votre singularité pour devenir l\'employeur de référence sur votre région.', href: '/architecture-de-marque/marque-employeur' },
      { num: '03', title: 'Santé et Sécurité au Travail', desc: 'Instaurez une culture de la vigilance qui protège vos équipes et votre réputation.', href: '/architecture-de-marque/communication-qhse' },
      { num: '04', title: 'Communication RSE', desc: 'Transformez votre communication RSE en actif de croissance et de valeur durable.', href: '/architecture-de-marque' },
      { num: '05', title: 'Événementiel Stratégique', desc: 'Orchestrez vos événements de bout en bout pour les convertir en levier stratégique.', href: '/evenements' },
      { num: '06', title: 'La Fabrique 360', desc: 'Matérialisez votre brand partout au Maroc avec une maîtrise totale de votre budget.', href: '/la-fabrique' },
    ],
  },
  {
    id: 'avantages',
    type: 'avantages',
    order: 60,
    title: 'Pourquoi choisir Epitaphe 360',
    items: [
      { title: 'Une maîtrise totale', desc: 'De l\'idée à l\'exécution, nous gérons vos projets de A à Z pour assurer cohérence, qualité et réactivité.' },
      { title: 'Une approche personnalisée', desc: 'Nos solutions sont adaptées à vos besoins uniques, avec des formules sur-mesure.' },
      { title: 'Un atelier interne', desc: 'Rapidité, flexibilité et réactivité sont nos garanties.' },
      { title: 'Une équipe passionnée', desc: 'Sur laquelle vous pouvez vraiment compter.' },
      { title: 'KPI et suivi', desc: 'Nous mesurons l\'impact de nos solutions pour optimiser votre ROI.' },
      { title: 'Un partenaire de confiance', desc: 'Qui optimise votre temps et vos budgets.' },
    ],
  },
  {
    id: 'commpulse',
    type: 'commpulse',
    order: 70,
    badge: 'BMI 360™',
    title: 'Évaluez la maturité de votre communication interne',
    body: 'Diagnostiquez en 5 minutes la performance de votre communication interne avec notre outil CommPulse — gratuit, anonyme, instantané.',
    ctaLabel: 'Lancer mon scoring CommPulse',
    ctaHref: '/outils/commpulse',
  },
  {
    id: 'fabrique',
    type: 'fabrique',
    order: 80,
    eyebrow: 'La Fabrique 360',
    title: 'Notre atelier intégré, votre avantage compétitif',
    body: 'De la conception à la pose, nous fabriquons vous-mêmes vos supports physiques pour garantir des délais courts, une qualité maîtrisée et des budgets optimisés.',
    services: [
      { title: 'Branding de siège et espaces corporate', href: '/la-fabrique/branding-siege' },
      { title: 'Stands et showrooms', href: '/la-fabrique' },
      { title: 'Enseignes et signalétique', href: '/la-fabrique' },
      { title: 'Impression et habillage physique', href: '/la-fabrique' },
      { title: 'Lettrage et découpe laser CNC', href: '/la-fabrique' },
      { title: 'PLV et dispositifs retail', href: '/la-fabrique' },
    ],
    images: [
      '/uploads/realisations/qatar-event.jpg',
      '/uploads/realisations/qatar-stand.jpg',
      '/uploads/realisations/renault-stand.jpg',
      '/uploads/realisations/snep-table.jpg',
    ],
    ctaLabel: 'Découvrir La Fabrique',
    ctaHref: '/la-fabrique',
  },
  {
    id: 'articles',
    type: 'articles',
    order: 90,
    title: 'Nos derniers articles',
    subtitle: 'Insights, méthodes et études de cas',
    limit: 3,
    ctaLabel: 'Voir tous les articles',
    ctaHref: '/blog',
  },
  {
    id: 'cta-final',
    type: 'cta',
    order: 100,
    title: 'Prêt à structurer votre influence ?',
    body: 'Discutons de votre projet et bâtissons ensemble une stratégie de communication à la hauteur de vos ambitions.',
    primaryCta: { label: 'Démarrer un projet', href: '/contact' },
    secondaryCta: { label: 'Voir nos réalisations', href: '/nos-references' },
    background: 'primary',
  },
];
